"""initial_schema

Revision ID: 3a54dd0eb627
Revises: 
Create Date: 2026-02-20 19:09:50.747001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a54dd0eb627'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('camp_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('openings_count', sa.Integer(), nullable=True),
    sa.Column('vibes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contribution_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('availability_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_profile_platform'), 'profile', ['platform'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_profile_platform_author_id'), 'profile', ['platform_author_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_profile_role'), 'profile', ['role'], unique=False, if_not_exists=True)
    op.create_table('post',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_community', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vibes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contribution_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('camp_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('camp_size_min', sa.Integer(), nullable=True),
    sa.Column('camp_size_max', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('location_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('availability_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_post_platform'), 'post', ['platform'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_post_platform_post_id'), 'post', ['platform_post_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_post_status'), 'post', ['status'], unique=False, if_not_exists=True)
    op.create_table('match',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seeker_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('camp_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seeker_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('camp_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('moderator_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intro_sent_at', sa.DateTime(), nullable=True),
    sa.Column('intro_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mismatch_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['camp_profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['seeker_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['seeker_profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_match_camp_post_id'), 'match', ['camp_post_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_match_seeker_post_id'), 'match', ['seeker_post_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_match_status'), 'match', ['status'], unique=False, if_not_exists=True)
    op.create_table('event',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_match_status'), table_name='match')
    op.drop_index(op.f('ix_match_seeker_post_id'), table_name='match')
    op.drop_index(op.f('ix_match_camp_post_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_post_status'), table_name='post')
    op.drop_index(op.f('ix_post_platform_post_id'), table_name='post')
    op.drop_index(op.f('ix_post_platform'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_profile_role'), table_name='profile')
    op.drop_index(op.f('ix_profile_platform_author_id'), table_name='profile')
    op.drop_index(op.f('ix_profile_platform'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
