"""add intro_draft to match

Revision ID: 47a9e3528006
Revises: 7b3e9a2f1c84
Create Date: 2026-02-22 12:48:44.882781

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47a9e3528006"
down_revision: str | None = "7b3e9a2f1c84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match", sa.Column("intro_draft", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "intro_draft")
    # ### end Alembic commands ###
