"""add intro_draft to match

Revision ID: 47a9e3528006
Revises: 7b3e9a2f1c84
Create Date: 2026-02-22 12:48:44.882781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47a9e3528006'
down_revision: Union[str, None] = '7b3e9a2f1c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('intro_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'intro_draft')
    # ### end Alembic commands ###
