"""add_infrastructure_fields

Revision ID: 4a8a055657bf
Revises: 3a54dd0eb627
Create Date: 2026-02-20 22:08:54.328982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a8a055657bf'
down_revision: Union[str, None] = '3a54dd0eb627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('post', sa.Column('infra_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post', sa.Column('infra_categories', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('post', sa.Column('quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post', sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post', sa.Column('dates_needed', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_post_post_type'), 'post', ['post_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_post_type'), table_name='post')
    op.drop_column('post', 'dates_needed')
    op.drop_column('post', 'condition')
    op.drop_column('post', 'quantity')
    op.drop_column('post', 'infra_categories')
    op.drop_column('post', 'infra_role')
    op.drop_column('post', 'post_type')
    # ### end Alembic commands ###
