"""add_skipped_reason_to_post

Revision ID: 53561b998723
Revises: f3be4be71e0a
Create Date: 2026-05-08 14:14:45.019853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53561b998723'
down_revision: Union[str, None] = 'f3be4be71e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('skipped_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'skipped_reason')
    # ### end Alembic commands ###
