"""add_origin_location_fields_to_post

Revision ID: 83e57d880def
Revises: f2b1c3d4e5f6
Create Date: 2026-03-15 20:49:25.797977

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83e57d880def"
down_revision: str | None = "f2b1c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("origin_location_raw", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("origin_location_city", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("origin_location_state", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("origin_location_county", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("origin_location_zip", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("origin_location_zip")
        batch_op.drop_column("origin_location_county")
        batch_op.drop_column("origin_location_state")
        batch_op.drop_column("origin_location_city")
        batch_op.drop_column("origin_location_raw")
    # ### end Alembic commands ###
