"""add_opted_out_to_post

Revision ID: a9fa3d135aaf
Revises: 83e57d880def
Create Date: 2026-04-06 15:11:23.113780

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9fa3d135aaf"
down_revision: str | None = "83e57d880def"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post",
        sa.Column("opted_out", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "opted_out")
    # ### end Alembic commands ###
