"""add_post_deduplication_fields

Revision ID: f3be4be71e0a
Revises: cde0fbf70a21
Create Date: 2026-05-08 13:06:21.016749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3be4be71e0a'
down_revision: Union[str, None] = 'cde0fbf70a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post', sa.Column('minhash_sigs', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post', sa.Column('parent_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_post_content_hash'), 'post', ['content_hash'], unique=False)
    op.create_index(op.f('ix_post_parent_post_id'), 'post', ['parent_post_id'], unique=False)
    op.create_foreign_key(None, 'post', 'post', ['parent_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_parent_post_id'), table_name='post')
    op.drop_index(op.f('ix_post_content_hash'), table_name='post')
    op.drop_column('post', 'parent_post_id')
    op.drop_column('post', 'minhash_sigs')
    op.drop_column('post', 'content_hash')
    # ### end Alembic commands ###
